# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - gci
    - gochecknoglobals
    - golint
    - ireturn
    - lll
    - nonamedreturns
    - varnamelen
    # Linter is deprecated.
    - maligned
    - scopelint
    # is disabled because of go1.18.
    - bodyclose
    - contextcheck
    - interfacer
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - wastedassign

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - dupl
        - funlen
        - goconst
        - goerr113
        - gomnd
        - maintidx
        - noctx
        - rowserrcheck
      path: "_test.go"
