name: test

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

env:
  GO_LATEST_VERSION: "1.18.x"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # Remove some platforms because of running out of quota.
        # os: [ ubuntu-latest, macos-latest ]
        # go-version: [ 1.17.x, 1.18.x ]
        os: [ ubuntu-latest ]
        go-version: [ 1.18.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go cache
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-cache

      - name: Test
        id: test
        run: |
          make test

      - name: Upload code coverage
        if: matrix.go-version == env.GO_LATEST_VERSION
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./unit.coverprofile,./signal.coverprofile
          flags: unittests-${{ runner.os }}
